from .gemini_client import ask_gemini


def generate_secure_code(code: str, vulnerabilities: list) -> str:
    vuln_text = "\n".join(
        [
            f"- {v.type} at line {v.line}: {v.description}"
            for v in vulnerabilities
        ]
    )

    prompt = f"""
You are a secure coding expert.

Rewrite the vulnerable code into a secure production-ready version.

RULES:
- preserve business logic
- fix all security issues
- use secure coding best practices
- output ONLY code
- no markdown
- no explanations

VULNERABILITIES:
{vuln_text}

CODE:
{code}
"""

    response = ask_gemini(prompt, mode="code")
    
    # Add verification comment to indicate AI-generated code
    if response and not response.startswith("ERROR:"):
        response = f"# This secure code was generated by Gemini AI\n# Source: gemini_ai_reasoning_engine\n\n{response}"
    
    return response